name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        ocaml-compiler:
          - ocaml-variants.4.12.0+domains
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install package dependencies
        run: opam install --deps-only --with-test .
      - name: Build and test
        run: opam exec -- dune build @install @runtest